project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
    - "programa.qmd"
    - "00-nivelacion1/*.qmd"
    - "00-nivelacion2/*.qmd"
    - "01-importar/*.qmd"
    - "02-transformar/*.qmd"
    - "03-visualizar/*.qmd"
    - "!04-comunicar/*.qmd"
    - "!05-inferencia/*.qmd"
    - "!06-regresion1/*.qmd"
    - "!07-regresion2/*.qmd"
    - "!08-eda/*.qmd"

website:
  title: "DIAPP 2026 · Análisis de Datos"
  favicon: img/logo-26.png
  navbar:
    left:
      - text: "🏠 Inicio"
        href: index.qmd
    right:
      - icon: github
        href: https://github.com/gduartez/diapp-2026

  sidebar:
    style: "docked"
    contents:
      - section: "Nivelación"
        contents:
        - text: "Clase 1: Estadística Descriptiva"
          href: 00-nivelacion1/nivelacion-01.html
        - text: "Clase 2: Inferencia Estadística"
          href: 00-nivelacion2/nivelacion-02.html
      - section: "Módulo 2"
        contents:
        - text: "Clase 1: Importar datos"
          href: 01-importar/clase-01.html
        - text: "Clase 2: Transformar datos"
          href: 02-transformar/clase-02.html
        - text: "Clase 3: Visualizar datos"
          href: 03-visualizar/clase-03.html
        - text: "Clase 4: Comunicar con R"
          href: 04-comunicar/clase-04.html
        - text: "Clase 5: Inferencia"
          href: 05-inferencia/clase-05.html
        - text: "Clase 6: Regresión I"
          href: 06-regresion1/clase-06.html
        - text: "Clase 7: Regresión II"
          href: 07-regresion2/clase-07.html
        - text: "Clase 8: Taller de cierre"
          href: 08-eda/clase-08.html

format:
  html:
    theme: united
    toc: true